apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  selector:
    app.kubernetes.io/name: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
