applications:
  - name: ${app_name}
    namespace: argocd
    project: default
    source:
      repoURL: ${repo_url}
      path: ${repo_path}
      targetRevision: HEAD
      helm:
        valueFiles: []
        parameters: []
    destination:
      server: https://kubernetes.default.svc
      namespace: ${destination_ns}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
