loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem

singleBinary:
  replicas: 1

persistence:
  enabled: true
  size: 5Gi

service:
  type: ClusterIP

# Install promtail DaemonSet to scrape logs from nodes/pods
promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - docker: {}
    clients:
      - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
