apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.96.0
    helm:
      values: |
        mode: daemonset
        image:
          repository: otel/opentelemetry-collector-contrib
        config:
          receivers:
            filelog:
              include:
                - /var/log/pods/*/*/*.log
              start_at: beginning
              include_file_name: false
              include_file_path: true
              resource:
                k8s.container.name: "${k8s.container.name}"
                k8s.namespace.name: "${k8s.namespace.name}"
                k8s.pod.name: "${k8s.pod.name}"
            otlp:
              protocols:
                http: {}
                grpc: {}
          processors:
            batch: {}
            k8sattributes:
              auth_type: serviceAccount
              extract:
                metadata:
                  - k8s.pod.name
                  - k8s.namespace.name
                  - k8s.pod.uid
                  - k8s.node.name
                  - k8s.pod.start_time
          exporters:
            loki:
              endpoint: http://loki:3100/loki/api/v1/push
              labels:
                resource:
                  k8s.namespace.name: "${k8s.namespace.name}"
                  k8s.pod.name: "${k8s.pod.name}"
                  k8s.container.name: "${k8s.container.name}"
          service:
            pipelines:
              logs:
                receivers: [filelog]
                processors: [k8sattributes, batch]
                exporters: [loki]
        tolerations:
          - operator: Exists
        extraVolumes:
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibcontainers
            hostPath:
              path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
        extraVolumeMounts:
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlibcontainers
            mountPath: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
