loki:
  loki:
    auth_enabled: false
  singleBinary:
    replicas: 1
  write:
    replicas: 0
  read:
    replicas: 0
  gateway:
    enabled: false

# Expose Loki service internally
  service:
    type: ClusterIP

# Grafana with a Loki datasource
grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:3100
          isDefault: true

opentelemetry-collector:
  mode: daemonset
  image:
    repository: otel/opentelemetry-collector-contrib
  config:
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        start_at: beginning
        include_file_name: false
        include_file_path: true
        resource:
          k8s.container.name: "${k8s.container.name}"
          k8s.namespace.name: "${k8s.namespace.name}"
          k8s.pod.name: "${k8s.pod.name}"
      # Also receive OTLP if needed in future
      otlp:
        protocols:
          http: {}
          grpc: {}
    processors:
      batch: {}
      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.pod.uid
            - k8s.node.name
            - k8s.pod.start_time
    exporters:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
        labels:
          resource:
            k8s.namespace.name: "${k8s.namespace.name}"
            k8s.pod.name: "${k8s.pod.name}"
            k8s.container.name: "${k8s.container.name}"
        # Optional: reduce cardinality / drop noisy fields
        # format: body
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [k8sattributes, batch]
          exporters: [loki]
  tolerations:
    - operator: Exists
  extraVolumes:
    - name: varlogpods
      hostPath:
        path: /var/log/pods
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  extraVolumeMounts:
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
