image:
  repository: nginx
  tag: "1.25.5"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources: {}

otel:
  endpoint: "http://otel-collector.observability.svc.cluster.local:4318"
