name: infra

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format
        working-directory: infra/terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      - name: tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0
      - name: Run tflint
        working-directory: infra/terraform
        run: |
          tflint --init
          tflint -f compact
